const config=window.GRANDMA_WATCH_CONFIG;
const liffRelease=Object.freeze({version:"1.0.0-rc.3",revision:"08da6f5",builtAt:"2026-08-18T02:23:33.873Z"});
const app=document.querySelector("#app"),subtitle=document.querySelector("#subtitle");
const escapeHtml=(value)=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const format=(value)=>value?new Intl.DateTimeFormat("ja-JP",{dateStyle:"short",timeStyle:"short",timeZone:"Asia/Tokyo"}).format(new Date(value)):"未取得";
const clock=(value)=>new Intl.DateTimeFormat("ja-JP",{hour:"2-digit",minute:"2-digit",hourCycle:"h23",timeZone:"Asia/Tokyo"}).format(new Date(value));
function relativeTime(value,now=new Date()){
  if(!value)return "未取得";const date=new Date(value),minutes=Math.max(0,Math.floor((now-date)/60_000));
  if(minutes<1)return "たった今";if(minutes<60)return `${minutes}分前`;if(minutes<360)return `${Math.floor(minutes/60)}時間${minutes%60?`${minutes%60}分`:""}前`;
  const day=value=>new Intl.DateTimeFormat("en-CA",{year:"numeric",month:"2-digit",day:"2-digit",timeZone:"Asia/Tokyo"}).format(value),today=day(now),target=day(date),yesterday=day(new Date(now.getTime()-86400_000));
  if(target===today)return `今日 ${clock(date)}`;if(target===yesterday)return `昨日 ${clock(date)}`;return format(date);
}
const releaseRevision=()=>liffRelease.revision.startsWith("__LIFF_")?"ローカル":liffRelease.revision;
const releaseBuiltAt=()=>liffRelease.builtAt.startsWith("__LIFF_")?"未公開":format(liffRelease.builtAt);

let liffInitialization;
async function initializeLine(){if(!config)throw new Error("config.jsが未設定です");liffInitialization??=liff.init({liffId:config.liffId});await liffInitialization;if(!liff.isLoggedIn()){liff.login({redirectUri:location.href});return new Promise(()=>{});}}
async function token(){await initializeLine();const value=liff.getIDToken();if(!value)throw new Error("LINE認証を取得できません");return value;}
async function api(base,action,{method="GET",body}={}){const idToken=await token();const response=await fetch(`${base}?action=${encodeURIComponent(action)}`,{method,headers:{authorization:`Bearer ${idToken}`,"content-type":"application/json"},body:body?JSON.stringify(body):undefined,cache:"no-store"});const data=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(data.message??"処理に失敗しました");error.code=data.code;error.requestId=data.requestId;throw error;}return data;}
function stateName(value){return {NORMAL:"見守り中",CAUTION:"少し気になる状態",REVIEW:"確認が必要です",EMERGENCY:"緊急確認が必要です"}[value]??"状態を確認中";}
function severityName(value){return {CAUTION:"注意",REVIEW:"要確認",EMERGENCY:"緊急"}[value]??"要確認";}
function alertReason(value){return {NO_COMMUNICATION:"端末からの通信が長時間届いていません",NO_LOCATION:"位置情報が長時間更新されていません",NO_ACTIVITY:"スマートフォンの操作が長時間確認できていません",LOW_BATTERY:"端末のバッテリーが少なくなっています",MORNING_NO_REPORT:"今日の通信がまだ確認できていません"}[value]??"見守り状態の確認が必要です";}
function metricSeverity(alerts,type){return alerts.find(value=>value.alertType===type)?.severity?.toLowerCase()??"normal";}
function metric(label,value,detail,severity="normal"){return `<div class="metric metric-${escapeHtml(severity)}"><span class="metric-label">${escapeHtml(label)}</span><strong>${escapeHtml(value)}</strong>${detail?`<small>${escapeHtml(detail)}</small>`:""}</div>`;}
function integrationName(value){return {ANDROID_INGEST:"端末データ受信",ALERT_ENGINE:"見守り判定",LINE_WEBHOOK:"LINE受信",LINE_PUSH:"LINE通知"}[value]??"見守りBackend";}
function invitationErrorMessage(error){const message=String(error?.message??"");if(message.includes("既に申請または登録"))return "このLINEアカウントは既に申請または登録されています。登録する家族本人のLINEで招待リンクを開いてください。";if(message.includes("招待が無効または期限切れ"))return "この招待リンクは使用済み、期限切れ、または無効です。ADMINに新しいリンクの発行を依頼してください。";if(message.includes("LINE認証"))return "LINE認証を確認できませんでした。LINEアプリ内でリンクを開き直してください。";const requestId=typeof error?.requestId==="string"&&/^[A-Za-z0-9._-]{1,100}$/.test(error.requestId)?` 問い合わせID: ${error.requestId}`:"";return `参加申請を送信できませんでした。通信状態を確認し、もう一度お試しください。${requestId}`;}
function showError(error){app.innerHTML=`<div class="error">${escapeHtml(error.message)}</div>`;}
function showLoading(){subtitle.textContent="読み込み中…";app.innerHTML='<section class="card" aria-busy="true">通信中です…</section>';}
function copyInputValue(input){input.focus();input.select();input.setSelectionRange(0,input.value.length);if(typeof document.execCommand==="function"&&document.execCommand("copy"))return Promise.resolve();if(navigator.clipboard?.writeText)return navigator.clipboard.writeText(input.value);return Promise.reject(new Error("clipboard unavailable"));}

function alertCards(items){
  if(!items.length)return "";
  return `<section class="alert-section"><h2>確認が必要なこと</h2>${items.map(alert=>`<article class="card alert-card severity-${escapeHtml(alert.severity).toLowerCase()}"><div class="alert-heading"><span class="severity">${escapeHtml(severityName(alert.severity))}</span><strong>${escapeHtml(alertReason(alert.alertType))}</strong></div><div class="row"><span>検知時刻</span><strong>${format(alert.detectedAt)}</strong></div><div class="assignee">${alert.assignee?`${escapeHtml(alert.assignee)}さんが対応中`:"まだ対応者が決まっていません"}</div><div class="actions">${alert.status==="OPEN"?`<button data-claim="${alert.id}">対応する</button>`:""}${alert.canRespond?`<button data-result="${alert.id}" data-value="CONTACT_OK">連絡でき、問題なし</button><button class="secondary" data-result="${alert.id}" data-value="NO_CONTACT">連絡がつかない</button><button class="secondary" data-result="${alert.id}" data-value="GOING_TO_HOME">家へ向かう</button><button class="secondary" data-other="${alert.id}">その他の結果</button>`:""}</div></article>`).join("")}</section>`;
}

function bindAlertActions(refresh){
  app.onclick=async event=>{
    const button=event.target.closest("button[data-claim],button[data-result],button[data-other]");if(!button||button.disabled)return;
    button.disabled=true;
    try{
      if(button.dataset.claim)await api(config.familyApiUrl,"claim",{method:"POST",body:{alertId:button.dataset.claim}});
      if(button.dataset.result)await api(config.familyApiUrl,"result",{method:"POST",body:{alertId:button.dataset.result,result:button.dataset.value}});
      if(button.dataset.other){const comment=prompt("対応結果を1〜500文字で入力してください");if(comment===null){button.disabled=false;return;}if(comment.trim().length<1||comment.length>500){alert("対応結果は1〜500文字で入力してください。");button.disabled=false;return;}await api(config.familyApiUrl,"result",{method:"POST",body:{alertId:button.dataset.other,result:"OTHER",comment}});}
      await refresh();
    }catch(_){button.disabled=false;alert("操作を完了できませんでした。最新の状態を確認して、もう一度お試しください。");}
  };
}

async function statusView(){
  const [value,alerts]=await Promise.all([api(config.familyApiUrl,"status"),api(config.familyApiUrl,"active-alert")]);
  subtitle.textContent="現在の状態";
  const communicationAlert=alerts.items.find(item=>item.alertType==="NO_COMMUNICATION"||item.alertType==="MORNING_NO_REPORT"),activityState=value.interactionAvailable===true?metricSeverity(alerts.items,"NO_ACTIVITY"):"attention";
  const management=value.viewer?.isAdmin===true?`<section class="card admin-management"><h2>管理</h2><p class="muted">BASIOを新しく登録するための一回限りのコードを発行します。</p><div class="actions"><button id="issue-enrollment-code" type="button">端末登録コードを発行</button></div><div id="enrollment-code-result" class="enrollment-result" aria-live="polite" hidden><p class="muted">端末登録コード</p><div class="enrollment-code"></div><p>15分間有効です。</p><p>有効期限（日本時間）: <strong class="enrollment-expiry"></strong></p><p class="muted">再発行する場合は画面を再読み込みしてください。</p></div><div id="enrollment-code-error" class="inline-error" role="alert" hidden></div></section>`:"";
  const actions=`${value.viewer?.canViewExactLocation===true?'<a class="button" href="?view=location">現在地を見る</a>':""}${value.phoneAvailable===true?'<a class="button secondary" href="?view=phone">電話する</a>':""}`;
  app.innerHTML=`<div class="subject-name">${escapeHtml(value.subjectDisplayName)}さんの見守り</div><section class="card status-card status-${escapeHtml(value.status).toLowerCase()}"><div class="state">${escapeHtml(stateName(value.status))}</div><div class="metric-grid">${metric("通信",relativeTime(value.lastCommunicationAt),"最終通信",communicationAlert?.severity?.toLowerCase()??(value.lastCommunicationAt?"normal":"attention"))}${metric("端末操作",value.interactionAvailable===true?relativeTime(value.lastUserPresentAt??value.lastUnlockedAt):"端末側で要設定","最終確認",activityState)}${metric("位置",value.lastLocationAt?value.locationLabel:"未取得",relativeTime(value.lastLocationAt),metricSeverity(alerts.items,"NO_LOCATION")!="normal"?metricSeverity(alerts.items,"NO_LOCATION"):value.lastLocationAt?"normal":"attention")}${metric("バッテリー",value.batteryPercent==null?"未取得":`${value.batteryPercent}%`,value.charging==null?"充電状態未取得":value.charging?"充電中":"充電していません",metricSeverity(alerts.items,"LOW_BATTERY"))}</div>${actions?`<div class="actions two-actions">${actions}</div>`:""}</section>${alertCards(alerts.items)}${management}`;
  bindAlertActions(statusView);
  if(value.viewer?.isAdmin!==true)return;
  const button=document.querySelector("#issue-enrollment-code"),result=document.querySelector("#enrollment-code-result"),error=document.querySelector("#enrollment-code-error");
  let requestStarted=false;
  button.onclick=async()=>{
    if(requestStarted)return;
    requestStarted=true;button.disabled=true;button.textContent="発行中…";error.hidden=true;
    try{
      const issued=await api(config.adminApiUrl,"device-enrollment-code",{method:"POST",body:{}});
      if(!/^[A-Za-z0-9]{12}$/.test(issued.enrollmentCode)||!Number.isFinite(Date.parse(issued.expiresAt)))throw new Error("invalid enrollment response");
      result.querySelector(".enrollment-code").textContent=issued.enrollmentCode;
      result.querySelector(".enrollment-expiry").textContent=format(issued.expiresAt);
      result.hidden=false;button.textContent="発行済み";
    }catch(_){
      error.textContent="登録コードを発行できませんでした。通信状態を確認し、少し待ってから再度お試しください。";error.hidden=false;button.textContent="端末登録コードを発行";
      setTimeout(()=>{requestStarted=false;button.disabled=false;},5000);
    }
  };
}
async function locationView(){const value=await api(config.familyApiUrl,"location");subtitle.textContent="現在地";app.innerHTML=`<section class="card"><div class="state">📍 ${escapeHtml(value.locationLabel)}</div><div class="row"><span>位置更新</span><strong>${format(value.updatedAt)}</strong></div>${value.latitude==null?"":`<div class="row"><span>緯度・経度</span><strong>${value.latitude}, ${value.longitude}</strong></div><div class="row"><span>精度</span><strong>±${value.accuracyM}m</strong></div><div class="actions"><a class="button" rel="external noreferrer" href="${escapeHtml(value.googleMapsUrl)}">地図を開く</a></div>`}</section>`;}
async function phoneView(){const value=await api(config.familyApiUrl,"phone");subtitle.textContent="電話";app.innerHTML=`<section class="card"><p>${escapeHtml(value.displayName)}に電話しますか？</p><div class="actions"><a class="button" rel="external" href="tel:${escapeHtml(value.phoneNumber)}">電話する</a></div></section>`;}
async function alertsView(){const value=await api(config.familyApiUrl,"active-alert");subtitle.textContent="対応状況";if(!value.items.length){app.innerHTML='<section class="card">現在対応が必要な通知はありません。</section>';return;}app.innerHTML=value.items.map(a=>`<section class="card"><div class="state">${severityName(a.severity)}</div><p>${escapeHtml(alertReason(a.alertType))}</p><p>${a.assignee?`${escapeHtml(a.assignee)}さんが対応中`:"担当者なし"}</p><div class="actions">${a.status==="OPEN"?`<button data-claim="${a.id}">私が確認します</button>`:""}${a.canRespond?`<button data-result="${a.id}" data-value="CONTACT_OK">問題なし</button><button class="secondary" data-result="${a.id}" data-value="NO_CONTACT">連絡がつかない</button><button class="secondary" data-result="${a.id}" data-value="GOING_TO_HOME">家へ向かう</button><button class="secondary" data-other="${a.id}">その他</button>`:""}${a.status==="ASSIGNED"&&a.canRelease?`<button class="danger" data-release="${a.id}">担当を解除</button>`:""}</div></section>`).join("");app.onclick=async e=>{const target=e.target.closest("button");if(!target)return;try{if(target.dataset.claim)await api(config.familyApiUrl,"claim",{method:"POST",body:{alertId:target.dataset.claim}});if(target.dataset.result)await api(config.familyApiUrl,"result",{method:"POST",body:{alertId:target.dataset.result,result:target.dataset.value}});if(target.dataset.other){const comment=prompt("その他の内容（1〜500文字）");if(comment)await api(config.familyApiUrl,"result",{method:"POST",body:{alertId:target.dataset.other,result:"OTHER",comment}});}if(target.dataset.release&&confirm("担当を解除しますか？"))await api(config.familyApiUrl,"unassign",{method:"POST",body:{alertId:target.dataset.release}});await alertsView();}catch(error){showError(error);}};}
async function settingsView(){const value=await api(config.familyApiUrl,"notification-settings");subtitle.textContent="通知設定";app.innerHTML=`<section class="card"><h2>自分への通知</h2><p class="muted">ここでは、システムが異常と判断したときに自分が受け取る通知を設定します。異常と判断する条件はADMINが管理します。</p><label>通知レベル<select id="level"><option value="IMPORTANT_ONLY">重要なときだけ</option><option value="CAUTION_AND_ABOVE">注意も通知</option><option value="CUSTOM">カスタム</option></select></label><label class="check"><input id="comm" type="checkbox"> 長時間通信なし</label><label class="check"><input id="loc" type="checkbox"> 位置更新なし</label><label class="check"><input id="activity" type="checkbox"> 長時間端末操作なし</label><label class="check"><input id="battery" type="checkbox"> 低バッテリー</label><div class="actions"><button id="save">保存</button></div><div id="settings-result" class="muted" aria-live="polite"></div></section>`;document.querySelector("#level").value=value.notification_level;document.querySelector("#comm").checked=value.notify_no_communication;document.querySelector("#loc").checked=value.notify_no_location;document.querySelector("#activity").checked=value.notify_no_activity;document.querySelector("#battery").checked=value.notify_low_battery;document.querySelector("#save").onclick=async()=>{const button=document.querySelector("#save");button.disabled=true;try{await api(config.familyApiUrl,"notification-settings",{method:"PUT",body:{notificationLevel:document.querySelector("#level").value,notifyNoCommunication:document.querySelector("#comm").checked,notifyNoLocation:document.querySelector("#loc").checked,notifyNoActivity:document.querySelector("#activity").checked,notifyLowBattery:document.querySelector("#battery").checked}});document.querySelector("#settings-result").textContent="保存しました。";}catch(_){document.querySelector("#settings-result").textContent="保存できませんでした。入力と通信状態を確認してください。";}finally{button.disabled=false;}};}
async function historyView(){const to=new Date(),from=new Date(to.getTime()-24*3600_000);const idToken=await token();const response=await fetch(`${config.familyApiUrl}?action=location-history&from=${encodeURIComponent(from.toISOString())}&to=${encodeURIComponent(to.toISOString())}`,{headers:{authorization:`Bearer ${idToken}`},cache:"no-store"});const value=await response.json();if(!response.ok)throw new Error(value.message);subtitle.textContent="位置履歴";app.innerHTML=`<section class="card">${value.items.map(item=>`<div class="item"><strong>${format(item.recorded_at)}</strong><br>${item.location_available?`${escapeHtml(item.latitude)}, ${escapeHtml(item.longitude)}`:"位置なし"}</div>`).join("")||"履歴はありません"}</section>`;}
function ruleSection(id,title,rules,{activity=false,battery=false}={}){
  if(battery)return `<fieldset class="rule-card"><legend>${escapeHtml(title)}</legend><label class="check"><input id="${id}-enabled" type="checkbox" ${rules.lowBatteryEnabled?"checked":""}> 監視する</label><label>注意とする残量（％）<input id="${id}-threshold" type="number" min="1" max="100" step="1" value="${rules.lowBatteryPercent}"></label><label class="check"><input id="${id}-notify" type="checkbox" ${rules.lowBatteryNotifyEnabled?"checked":""}> LINE通知を許可する</label></fieldset>`;
  const prefix=activity?"activity":id,enabled=rules[`${prefix}Enabled`],caution=rules[`${prefix}CautionMin`]/60,review=rules[`${prefix}ReviewMin`]/60,notify=rules[`${prefix}NotifyEnabled`];
  return `<fieldset class="rule-card"><legend>${escapeHtml(title)}</legend><label class="check"><input id="${id}-enabled" type="checkbox" ${enabled?"checked":""}> 監視する</label>${activity?`<div class="two-fields"><label>開始<input id="activity-start" type="time" value="${escapeHtml(rules.activeStartTime)}"></label><label>終了<input id="activity-end" type="time" value="${escapeHtml(rules.activeEndTime)}"></label></div>`:""}<div class="two-fields"><label>注意とするまで（時間）<input id="${id}-caution" type="number" min="0.5" max="24" step="0.5" value="${caution}"></label><label>確認が必要となるまで（時間）<input id="${id}-review" type="number" min="1" max="24" step="0.5" value="${review}"></label></div><label class="check"><input id="${id}-notify" type="checkbox" ${notify?"checked":""}> LINE通知を許可する</label></fieldset>`;
}
async function systemView(){
  const [system,device,rules,home]=await Promise.all([api(config.adminApiUrl,"system-status"),api(config.adminApiUrl,"device-status"),api(config.adminApiUrl,"monitoring-rules"),api(config.adminApiUrl,"home-settings")]);
  subtitle.textContent="管理・設定";
  const healthHtml=device.enrolled?`<section class="card health-card"><h2>見守りシステム</h2><div class="overall ${device.health.overall==="OK"?"ok":"attention"}">${device.health.overall==="OK"?"正常に動いています":"確認が必要な項目があります"}</div>${device.health.items.map(item=>`<div class="row"><span>${escapeHtml(item.label)}</span><strong class="health-${item.status.toLowerCase()}">${escapeHtml(item.message)}</strong></div>`).join("")}</section>`:"";
  const deviceHtml=device.enrolled?`<section class="card"><h2>端末診断</h2><div class="row"><span>端末登録</span><strong>${device.active?"登録済み・稼働中":"停止中"}</strong></div><div class="row"><span>最終通信</span><strong>${relativeTime(device.lastCommunicationAt)}</strong></div><div class="row"><span>最終位置取得</span><strong>${relativeTime(device.lastLocationAt)}</strong></div><div class="row"><span>最終端末操作</span><strong>${device.interactionAvailable?relativeTime(device.lastUserPresentAt??device.lastUnlockedAt):"端末側で要設定"}</strong></div><div class="row"><span>バッテリー</span><strong>${device.batteryPercent==null?"未取得":`${device.batteryPercent}%`}</strong></div><div class="row"><span>充電状態</span><strong>${device.charging==null?"未取得":device.charging?"充電中":"充電していません"}</strong></div><div class="row"><span>ネットワーク</span><strong>${device.networkAvailable==null?"不明":device.networkAvailable?"利用可能":"利用できません"}</strong></div><div class="row"><span>位置情報取得</span><strong>${device.locationAvailable==null?"不明":device.locationAvailable?"取得できています":"取得できていません"}</strong></div><div class="row"><span>使用状況アクセス</span><strong>${device.interactionAvailable?"許可済み":"端末側で要設定"}</strong></div><div class="row"><span>Android</span><strong>${escapeHtml(device.androidVersion)}</strong></div><div class="row"><span>アプリ</span><strong>${escapeHtml(device.lastReportAppVersion??device.enrolledAppVersion)}</strong></div></section>`:'<section class="card"><h2>端末診断</h2><p>登録済み端末はありません。</p></section>';
  const rulesHtml=`<section class="card"><h2>見守り設定</h2><p class="muted">ここでは、何を異常と判断するかをADMINが設定します。家族ごとの通知希望とは別です。</p>${ruleSection("communication","通信がないとき",rules)}${ruleSection("location","位置更新がないとき",rules)}${ruleSection("activity","スマートフォンの操作がないとき",rules,{activity:true})}${ruleSection("battery","低バッテリー",rules,{battery:true})}<div class="actions"><button id="save-rules" type="button">見守り設定を保存</button></div><div id="rules-message" class="inline-message" aria-live="polite"></div></section>`;
  const latest=home.latestLocation,homeHtml=`<section class="card"><h2>自宅設定</h2><div class="row"><span>現在の登録</span><strong>${home.homeSet?"設定済み":"未設定"}</strong></div><label>自宅判定半径（50〜2000m）<input id="home-radius" type="number" min="50" max="2000" step="10" value="${home.radiusM}"></label><p class="muted">端末の最新位置: ${relativeTime(latest.updatedAt)}${latest.accuracyM==null?"":` / 精度 ±${escapeHtml(latest.accuracyM)}m`}</p>${latest.usable?"":'<p class="inline-error">位置が2時間より古い、または精度が200mを超えているため現在は登録できません。</p>'}<div class="actions"><button id="set-home" type="button" ${latest.usable?"":"disabled"}>現在の端末位置を自宅として設定</button></div><div id="home-message" class="inline-message" aria-live="polite"></div></section>`;
  const releaseHtml=`<section class="card"><h2>家族画面</h2><div class="row"><span>バージョン</span><strong>${escapeHtml(liffRelease.version)}</strong></div><div class="row"><span>ビルドID</span><strong>${escapeHtml(releaseRevision())}</strong></div><div class="row"><span>公開日時</span><strong>${escapeHtml(releaseBuiltAt())}</strong></div></section>`;
  app.innerHTML=`${healthHtml}${deviceHtml}${rulesHtml}${homeHtml}${releaseHtml}<section class="card"><h2>連携状態</h2>${system.items.map(item=>`<div class="row"><span>${escapeHtml(integrationName(item.component))}</span><strong>${escapeHtml(item.status==="OK"?"正常":"確認が必要")}</strong></div>`).join("")||"状態記録なし"}</section>`;
  const checked=id=>document.querySelector(`#${id}`).checked,hours=id=>Math.round(Number(document.querySelector(`#${id}`).value)*60),message=document.querySelector("#rules-message");
  document.querySelector("#save-rules").onclick=async event=>{event.currentTarget.disabled=true;message.textContent="";try{await api(config.adminApiUrl,"monitoring-rules",{method:"PUT",body:{communicationEnabled:checked("communication-enabled"),communicationCautionMin:hours("communication-caution"),communicationReviewMin:hours("communication-review"),communicationNotifyEnabled:checked("communication-notify"),locationEnabled:checked("location-enabled"),locationCautionMin:hours("location-caution"),locationReviewMin:hours("location-review"),locationNotifyEnabled:checked("location-notify"),activityEnabled:checked("activity-enabled"),activeStartTime:document.querySelector("#activity-start").value,activeEndTime:document.querySelector("#activity-end").value,activityCautionMin:hours("activity-caution"),activityReviewMin:hours("activity-review"),activityNotifyEnabled:checked("activity-notify"),lowBatteryEnabled:checked("battery-enabled"),lowBatteryPercent:Number(document.querySelector("#battery-threshold").value),lowBatteryNotifyEnabled:checked("battery-notify")}});message.textContent="見守り設定を保存しました。";}catch(error){message.textContent=error.message||"保存できませんでした。入力値を確認してください。";}finally{event.currentTarget.disabled=false;}};
  document.querySelector("#set-home").onclick=async event=>{if(!confirm("現在の見守り端末の位置を自宅として登録しますか？"))return;event.currentTarget.disabled=true;const homeMessage=document.querySelector("#home-message");try{await api(config.adminApiUrl,"home-settings",{method:"PUT",body:{useCurrentDeviceLocation:true,radiusM:Number(document.querySelector("#home-radius").value)}});homeMessage.textContent="自宅設定を保存しました。";await systemView();}catch(error){homeMessage.textContent=error.message||"自宅設定を保存できませんでした。";event.currentTarget.disabled=false;}};
}
async function familyView(){
  const value=await api(config.adminApiUrl,"family-members");subtitle.textContent="家族管理";
  app.innerHTML=`<section class="card">${value.items.map(m=>`<div class="item"><strong>${escapeHtml(m.display_name)}</strong> <span class="badge">${m.role}</span><br><span class="muted">${m.status} / 詳細位置 ${m.can_view_exact_location?"許可":"不可"} / 履歴 ${m.can_view_history?"許可":"不可"}</span>${m.status==="PENDING"?`<button data-approve="${m.id}">承認</button>`:""}</div>`).join("")}<div class="actions"><button id="invite" type="button">家族を招待する</button></div><div id="invite-result" class="enrollment-result" aria-live="polite" hidden><p>このリンクを登録する家族へ送ってください。24時間・1回限り有効です。</p><label>招待リンク<input id="invite-link" type="text" readonly></label><div class="actions"><button id="copy-invite" type="button">招待リンクをコピー</button></div><p id="invite-status" class="muted"></p></div><div id="invite-error" class="inline-error" role="alert" hidden></div></section>`;
  app.onclick=async e=>{
    const button=e.target.closest("button");if(!button||button.disabled)return;
    if(button.dataset.approve){button.disabled=true;try{await api(config.adminApiUrl,"approve-family",{method:"POST",body:{memberId:button.dataset.approve}});await familyView();}catch(_){button.disabled=false;alert("承認できませんでした。最新の状態を確認してください。");}return;}
    const result=document.querySelector("#invite-result"),inviteLink=document.querySelector("#invite-link"),status=document.querySelector("#invite-status"),error=document.querySelector("#invite-error");
    if(button.id==="invite"){
      button.disabled=true;button.textContent="発行中…";error.hidden=true;
      try{const invitation=await api(config.adminApiUrl,"create-invitation",{method:"POST",body:{}});inviteLink.value=`https://liff.line.me/${encodeURIComponent(config.liffId)}/?view=join&token=${encodeURIComponent(invitation.token)}`;result.hidden=false;button.textContent="発行済み";status.textContent="新しいリンクを表示しました。先頭は毎回同じで、末尾のtokenが発行ごとに変わります。";}
      catch(_){error.textContent="招待リンクを発行できませんでした。通信状態を確認し、少し待ってから再度お試しください。";error.hidden=false;button.disabled=false;button.textContent="家族を招待する";}return;
    }
    if(button.id==="copy-invite"){
      button.disabled=true;try{await copyInputValue(inviteLink);status.textContent="招待リンクをコピーしました。";}catch(_){status.textContent="自動コピーできませんでした。リンク欄を長押ししてコピーしてください。";}finally{button.disabled=false;}return;
    }
  };
}
async function joinView(){
  const inviteToken=new URLSearchParams(location.search).get("token")??"";subtitle.textContent="家族参加申請";
  app.innerHTML=`<section class="card"><p>見守りグループへの参加を申請します。登録する家族本人のLINEで入力してください。</p><label>表示名<input id="name" maxlength="100" autocomplete="name" required></label><label>続柄<input id="relation" maxlength="50" required></label><div class="actions"><button id="apply" type="button">参加申請</button></div><div id="join-error" class="inline-error" role="alert" hidden></div></section>`;
  const button=document.querySelector("#apply"),error=document.querySelector("#join-error");
  button.onclick=async()=>{
    if(button.disabled)return;error.hidden=true;
    const displayName=document.querySelector("#name").value.trim(),relation=document.querySelector("#relation").value.trim();
    if(inviteToken.length<32){error.textContent="招待リンクが無効です。ADMINに新しいリンクの発行を依頼してください。";error.hidden=false;return;}
    if(!displayName||!relation){error.textContent="表示名と続柄を両方入力してください。";error.hidden=false;return;}
    button.disabled=true;button.textContent="申請中…";
    try{await api(config.familyApiUrl,"apply-invitation",{method:"POST",body:{token:inviteToken,displayName,relation}});app.innerHTML='<section class="card"><h2>参加申請を送信しました</h2><p>ADMINの承認後に見守り情報を確認できます。</p></section>';}
    catch(cause){error.textContent=invitationErrorMessage(cause);error.hidden=false;button.disabled=false;button.textContent="参加申請";}
  };
}

const views={status:statusView,location:locationView,phone:phoneView,history:historyView,alerts:alertsView,settings:settingsView,family:familyView,system:systemView,join:joinView};
async function start(){showLoading();await initializeLine();const selected=views[new URLSearchParams(location.search).get("view")??"status"];if(!selected)throw new Error("画面が見つかりません");await selected();}
start().catch(showError);
