const config=window.GRANDMA_WATCH_CONFIG;
const app=document.querySelector("#app"),subtitle=document.querySelector("#subtitle");
const escapeHtml=(value)=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const format=(value)=>value?new Intl.DateTimeFormat("ja-JP",{dateStyle:"short",timeStyle:"short",timeZone:"Asia/Tokyo"}).format(new Date(value)):"未取得";

async function token(){if(!config)throw new Error("config.jsが未設定です");await liff.init({liffId:config.liffId});if(!liff.isLoggedIn()){liff.login();return new Promise(()=>{});}const value=liff.getIDToken();if(!value)throw new Error("LINE認証を取得できません");return value;}
async function api(base,action,{method="GET",body}={}){const idToken=await token();const response=await fetch(`${base}?action=${encodeURIComponent(action)}`,{method,headers:{authorization:`Bearer ${idToken}`,"content-type":"application/json"},body:body?JSON.stringify(body):undefined,cache:"no-store"});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message??"処理に失敗しました");return data;}
function stateName(value){return {NORMAL:"見守り中",CAUTION:"少し気になる状態",REVIEW:"確認が必要です",EMERGENCY:"緊急確認が必要です"}[value]??"状態を確認中";}
function severityName(value){return {CAUTION:"注意",REVIEW:"要確認",EMERGENCY:"緊急"}[value]??"要確認";}
function alertReason(value){return {NO_COMMUNICATION:"端末からの通信が長時間届いていません",NO_LOCATION:"位置情報が長時間更新されていません",LOW_BATTERY:"端末のバッテリーが少なくなっています",MORNING_NO_REPORT:"今日の通信がまだ確認できていません"}[value]??"見守り状態の確認が必要です";}
function showError(error){app.innerHTML=`<div class="error">${escapeHtml(error.message)}</div>`;}
function showLoading(){subtitle.textContent="読み込み中…";app.innerHTML='<section class="card" aria-busy="true">通信中です…</section>';}

function alertCards(items){
  if(!items.length)return "";
  return `<section class="alert-section"><h2>確認が必要なこと</h2>${items.map(alert=>`<article class="card alert-card severity-${escapeHtml(alert.severity).toLowerCase()}"><div class="alert-heading"><span class="severity">${escapeHtml(severityName(alert.severity))}</span><strong>${escapeHtml(alertReason(alert.alertType))}</strong></div><div class="row"><span>検知時刻</span><strong>${format(alert.detectedAt)}</strong></div><div class="assignee">${alert.assignee?`${escapeHtml(alert.assignee)}さんが対応中`:"まだ対応者が決まっていません"}</div><div class="actions">${alert.status==="OPEN"?`<button data-claim="${alert.id}">対応する</button>`:""}${alert.canRespond?`<button data-result="${alert.id}" data-value="CONTACT_OK">連絡でき、問題なし</button><button class="secondary" data-result="${alert.id}" data-value="NO_CONTACT">連絡がつかない</button><button class="secondary" data-result="${alert.id}" data-value="GOING_TO_HOME">家へ向かう</button><button class="secondary" data-other="${alert.id}">その他の結果</button>`:""}</div></article>`).join("")}</section>`;
}

function bindAlertActions(refresh){
  app.onclick=async event=>{
    const button=event.target.closest("button[data-claim],button[data-result],button[data-other]");if(!button||button.disabled)return;
    button.disabled=true;
    try{
      if(button.dataset.claim)await api(config.familyApiUrl,"claim",{method:"POST",body:{alertId:button.dataset.claim}});
      if(button.dataset.result)await api(config.familyApiUrl,"result",{method:"POST",body:{alertId:button.dataset.result,result:button.dataset.value}});
      if(button.dataset.other){const comment=prompt("対応結果を1〜500文字で入力してください");if(comment===null){button.disabled=false;return;}if(comment.trim().length<1||comment.length>500){alert("対応結果は1〜500文字で入力してください。");button.disabled=false;return;}await api(config.familyApiUrl,"result",{method:"POST",body:{alertId:button.dataset.other,result:"OTHER",comment}});}
      await refresh();
    }catch(_){button.disabled=false;alert("操作を完了できませんでした。最新の状態を確認して、もう一度お試しください。");}
  };
}

async function statusView(){
  const [value,alerts]=await Promise.all([api(config.familyApiUrl,"status"),api(config.familyApiUrl,"active-alert")]);
  subtitle.textContent="現在の状態";
  const management=value.viewer?.isAdmin===true?`<section class="card admin-management"><h2>管理</h2><p class="muted">BASIOを新しく登録するための一回限りのコードを発行します。</p><div class="actions"><button id="issue-enrollment-code" type="button">端末登録コードを発行</button></div><div id="enrollment-code-result" class="enrollment-result" aria-live="polite" hidden><p class="muted">端末登録コード</p><div class="enrollment-code"></div><p>15分間有効です。</p><p>有効期限（日本時間）: <strong class="enrollment-expiry"></strong></p><p class="muted">再発行する場合は画面を再読み込みしてください。</p></div><div id="enrollment-code-error" class="inline-error" role="alert" hidden></div></section>`:"";
  const actions=`${value.viewer?.canViewExactLocation===true?'<a class="button" href="?view=location">現在地を見る</a>':""}${value.phoneAvailable===true?'<a class="button secondary" href="?view=phone">電話する</a>':""}`;
  app.innerHTML=`<div class="subject-name">${escapeHtml(value.subjectDisplayName)}さんの見守り</div><section class="card status-card status-${escapeHtml(value.status).toLowerCase()}"><div class="state">${escapeHtml(stateName(value.status))}</div><div class="row"><span>最終通信</span><strong>${format(value.lastCommunicationAt)}</strong></div><div class="row"><span>最終位置取得</span><strong>${format(value.lastLocationAt)}</strong></div><div class="row"><span>現在地</span><strong>${escapeHtml(value.locationLabel)}</strong></div><div class="row"><span>バッテリー</span><strong>${value.batteryPercent==null?"未取得":`${value.batteryPercent}%`}</strong></div><div class="row"><span>充電</span><strong>${value.charging==null?"未取得":value.charging?"充電中":"充電していません"}</strong></div>${actions?`<div class="actions two-actions">${actions}</div>`:""}</section>${alertCards(alerts.items)}${management}`;
  bindAlertActions(statusView);
  if(value.viewer?.isAdmin!==true)return;
  const button=document.querySelector("#issue-enrollment-code"),result=document.querySelector("#enrollment-code-result"),error=document.querySelector("#enrollment-code-error");
  let requestStarted=false;
  button.onclick=async()=>{
    if(requestStarted)return;
    requestStarted=true;button.disabled=true;button.textContent="発行中…";error.hidden=true;
    try{
      const issued=await api(config.adminApiUrl,"device-enrollment-code",{method:"POST",body:{}});
      if(!/^[A-Za-z0-9]{12}$/.test(issued.enrollmentCode)||!Number.isFinite(Date.parse(issued.expiresAt)))throw new Error("invalid enrollment response");
      result.querySelector(".enrollment-code").textContent=issued.enrollmentCode;
      result.querySelector(".enrollment-expiry").textContent=format(issued.expiresAt);
      result.hidden=false;button.textContent="発行済み";
    }catch(_){
      error.textContent="登録コードを発行できませんでした。通信状態を確認し、少し待ってから再度お試しください。";error.hidden=false;button.textContent="端末登録コードを発行";
      setTimeout(()=>{requestStarted=false;button.disabled=false;},5000);
    }
  };
}
async function locationView(){const value=await api(config.familyApiUrl,"location");subtitle.textContent="現在地";app.innerHTML=`<section class="card"><div class="state">📍 ${escapeHtml(value.locationLabel)}</div><div class="row"><span>位置更新</span><strong>${format(value.updatedAt)}</strong></div>${value.latitude==null?"":`<div class="row"><span>緯度・経度</span><strong>${value.latitude}, ${value.longitude}</strong></div><div class="row"><span>精度</span><strong>±${value.accuracyM}m</strong></div><div class="actions"><a class="button" rel="external noreferrer" href="${escapeHtml(value.googleMapsUrl)}">地図を開く</a></div>`}</section>`;}
async function phoneView(){const value=await api(config.familyApiUrl,"phone");subtitle.textContent="電話";app.innerHTML=`<section class="card"><p>${escapeHtml(value.displayName)}に電話しますか？</p><div class="actions"><a class="button" rel="external" href="tel:${escapeHtml(value.phoneNumber)}">電話する</a></div></section>`;}
async function alertsView(){const value=await api(config.familyApiUrl,"active-alert");subtitle.textContent="対応状況";if(!value.items.length){app.innerHTML='<section class="card">現在対応が必要な通知はありません。</section>';return;}app.innerHTML=value.items.map(a=>`<section class="card"><div class="state">${severityName(a.severity)}</div><p>${escapeHtml(alertReason(a.alertType))}</p><p>${a.assignee?`${escapeHtml(a.assignee)}さんが対応中`:"担当者なし"}</p><div class="actions">${a.status==="OPEN"?`<button data-claim="${a.id}">私が確認します</button>`:""}${a.canRespond?`<button data-result="${a.id}" data-value="CONTACT_OK">問題なし</button><button class="secondary" data-result="${a.id}" data-value="NO_CONTACT">連絡がつかない</button><button class="secondary" data-result="${a.id}" data-value="GOING_TO_HOME">家へ向かう</button><button class="secondary" data-other="${a.id}">その他</button>`:""}${a.status==="ASSIGNED"&&a.canRelease?`<button class="danger" data-release="${a.id}">担当を解除</button>`:""}</div></section>`).join("");app.onclick=async e=>{const target=e.target.closest("button");if(!target)return;try{if(target.dataset.claim)await api(config.familyApiUrl,"claim",{method:"POST",body:{alertId:target.dataset.claim}});if(target.dataset.result)await api(config.familyApiUrl,"result",{method:"POST",body:{alertId:target.dataset.result,result:target.dataset.value}});if(target.dataset.other){const comment=prompt("その他の内容（1〜500文字）");if(comment)await api(config.familyApiUrl,"result",{method:"POST",body:{alertId:target.dataset.other,result:"OTHER",comment}});}if(target.dataset.release&&confirm("担当を解除しますか？"))await api(config.familyApiUrl,"unassign",{method:"POST",body:{alertId:target.dataset.release}});await alertsView();}catch(error){showError(error);}};}
async function settingsView(){const value=await api(config.familyApiUrl,"notification-settings");subtitle.textContent="通知設定";app.innerHTML=`<section class="card"><label>通知レベル<select id="level"><option value="IMPORTANT_ONLY">重要なときだけ</option><option value="CAUTION_AND_ABOVE">注意も通知</option><option value="CUSTOM">カスタム</option></select></label><label><input id="comm" type="checkbox"> 長時間通信なし</label><label><input id="loc" type="checkbox"> 位置更新なし</label><label><input id="battery" type="checkbox"> 低バッテリー</label><div class="actions"><button id="save">保存</button></div></section>`;document.querySelector("#level").value=value.notification_level;document.querySelector("#comm").checked=value.notify_no_communication;document.querySelector("#loc").checked=value.notify_no_location;document.querySelector("#battery").checked=value.notify_low_battery;document.querySelector("#save").onclick=async()=>{await api(config.familyApiUrl,"notification-settings",{method:"PUT",body:{notificationLevel:document.querySelector("#level").value,notifyNoCommunication:document.querySelector("#comm").checked,notifyNoLocation:document.querySelector("#loc").checked,notifyLowBattery:document.querySelector("#battery").checked}});subtitle.textContent="保存しました";};}
async function historyView(){const to=new Date(),from=new Date(to.getTime()-24*3600_000);const idToken=await token();const response=await fetch(`${config.familyApiUrl}?action=location-history&from=${encodeURIComponent(from.toISOString())}&to=${encodeURIComponent(to.toISOString())}`,{headers:{authorization:`Bearer ${idToken}`},cache:"no-store"});const value=await response.json();if(!response.ok)throw new Error(value.message);subtitle.textContent="位置履歴";app.innerHTML=`<section class="card">${value.items.map(item=>`<div class="item"><strong>${format(item.recorded_at)}</strong><br>${item.location_available?`${escapeHtml(item.latitude)}, ${escapeHtml(item.longitude)}`:"位置なし"}</div>`).join("")||"履歴はありません"}</section>`;}
async function systemView(){const [value,device]=await Promise.all([api(config.adminApiUrl,"system-status"),api(config.adminApiUrl,"device-status")]);subtitle.textContent="システム状態";const deviceHtml=device.enrolled?`<section class="card"><h2>端末状態</h2><div class="row"><span>機種</span><strong>${escapeHtml(device.deviceModel)}</strong></div><div class="row"><span>Android</span><strong>${escapeHtml(device.androidVersion)}</strong></div><div class="row"><span>アプリ</span><strong>${escapeHtml(device.lastReportAppVersion??device.enrolledAppVersion)}</strong></div><div class="row"><span>最終認証</span><strong>${format(device.lastAuthenticatedAt)}</strong></div><div class="row"><span>最終通信</span><strong>${format(device.lastCommunicationAt)}</strong></div><div class="row"><span>最終位置</span><strong>${format(device.lastLocationAt)}</strong></div><div class="row"><span>最終レポート時の通信</span><strong>${device.networkAvailable==null?"不明":device.networkAvailable?"利用可":"利用不可"}</strong></div><div class="row"><span>稼働</span><strong>${device.active?"有効":"停止"}</strong></div></section>`:'<section class="card">登録済み端末はありません。</section>';app.innerHTML=`${deviceHtml}<section class="card"><h2>連携状態</h2>${value.items.map(item=>`<div class="row"><span>${escapeHtml(item.component)}</span><strong>${escapeHtml(item.status)}</strong></div>`).join("")||"状態記録なし"}</section>`;}
async function familyView(){const value=await api(config.adminApiUrl,"family-members");subtitle.textContent="家族管理";app.innerHTML=`<section class="card">${value.items.map(m=>`<div class="item"><strong>${escapeHtml(m.display_name)}</strong> <span class="badge">${m.role}</span><br><span class="muted">${m.status} / 詳細位置 ${m.can_view_exact_location?"許可":"不可"} / 履歴 ${m.can_view_history?"許可":"不可"}</span>${m.status==="PENDING"?`<button data-approve="${m.id}">承認</button>`:""}</div>`).join("")}<div class="actions"><button id="invite">招待リンクを発行</button></div></section>`;app.onclick=async e=>{const button=e.target.closest("button");if(button?.dataset.approve){await api(config.adminApiUrl,"approve-family",{method:"POST",body:{memberId:button.dataset.approve}});await familyView();}if(button?.id==="invite"){const invitation=await api(config.adminApiUrl,"create-invitation",{method:"POST",body:{}});await navigator.clipboard.writeText(`${location.origin}${location.pathname}?view=join&token=${encodeURIComponent(invitation.token)}`);alert("招待リンクをコピーしました。tokenはこの表示後に保存しないでください。");}};}
async function joinView(){const inviteToken=new URLSearchParams(location.search).get("token")??"";subtitle.textContent="家族参加申請";app.innerHTML=`<section class="card"><label>表示名<input id="name" maxlength="100"></label><label>続柄<input id="relation" maxlength="50"></label><div class="actions"><button id="apply">参加申請</button></div></section>`;document.querySelector("#apply").onclick=async()=>{await api(config.familyApiUrl,"apply-invitation",{method:"POST",body:{token:inviteToken,displayName:document.querySelector("#name").value,relation:document.querySelector("#relation").value}});app.innerHTML='<section class="card">申請しました。ADMINの承認をお待ちください。</section>';};}

const views={status:statusView,location:locationView,phone:phoneView,history:historyView,alerts:alertsView,settings:settingsView,family:familyView,system:systemView,join:joinView};
const selected=views[new URLSearchParams(location.search).get("view")??"status"];
showLoading();
(selected?selected():Promise.reject(new Error("画面が見つかりません"))).catch(showError);
